#!/usr/bin/env node
/* ════════════════════════════════════════════════════════════════════════
   bootstrap-users.js — seed the two owner users after migrations/0001
   has been applied.

   What it does:
     1. Prompts for a password (or reads $BOOTSTRAP_PASSWORD)
     2. Hashes it with PBKDF2-SHA256 (same params as the worker)
     3. Prints two INSERT statements for the two owner accounts:
          - mail@markschofield.org
          - mail@signingworks.co.uk
        BOTH share this initial password — change them after first login.

   Usage:
     # Apply schema first:
     wrangler d1 execute deafhive --remote \
       --file=worker-v2/migrations/0001-add-users.sql

     # Then generate + apply the seed in one go:
     node worker-v2/bootstrap-users.js > worker-v2/.bootstrap-users.sql
     wrangler d1 execute deafhive --remote \
       --file=worker-v2/.bootstrap-users.sql
     rm worker-v2/.bootstrap-users.sql   # contains hashed password — keep
                                          # OFF git (already in .gitignore)

   You can re-run safely — the INSERT uses ON CONFLICT(email) DO UPDATE,
   so existing rows get their password reset to the new value.
   ════════════════════════════════════════════════════════════════════════ */

import { webcrypto as crypto } from 'node:crypto';
import readline from 'node:readline/promises';
import { stdin as input, stdout as output, stderr } from 'node:process';

const ITERATIONS = 100_000;
const SALT_BYTES = 16;
const HASH_BYTES = 32;

const OWNERS = [
  { email: 'mail@markschofield.org',  display_name: 'Mark Schofield' },
  { email: 'mail@signingworks.co.uk', display_name: 'Signingworks'    },
];

function bytesToBase64Url(bytes) {
  let bin = '';
  for (const b of bytes) bin += String.fromCharCode(b);
  return Buffer.from(bin, 'binary').toString('base64')
    .replace(/=+$/, '').replace(/\+/g, '-').replace(/\//g, '_');
}

async function pbkdf2(passwordBytes, salt, iterations, hashBytes) {
  const baseKey = await crypto.subtle.importKey(
    'raw', passwordBytes, { name: 'PBKDF2' }, false, ['deriveBits'],
  );
  const derived = await crypto.subtle.deriveBits(
    { name: 'PBKDF2', hash: 'SHA-256', salt, iterations },
    baseKey,
    hashBytes * 8,
  );
  return new Uint8Array(derived);
}

async function hashPassword(plain) {
  const salt = crypto.getRandomValues(new Uint8Array(SALT_BYTES));
  const hash = await pbkdf2(
    new TextEncoder().encode(plain), salt, ITERATIONS, HASH_BYTES,
  );
  return `${ITERATIONS}.${bytesToBase64Url(salt)}.${bytesToBase64Url(hash)}`;
}

function sqlString(v) {
  if (v == null) return 'NULL';
  return `'${String(v).replace(/'/g, "''")}'`;
}

async function main() {
  // Read password from env or prompt (hidden via tty when possible).
  let password = process.env.BOOTSTRAP_PASSWORD;
  if (!password) {
    // Emit prompt to stderr so SQL output (stdout) stays clean.
    const rl = readline.createInterface({ input, output: stderr });
    password = (await rl.question('Bootstrap admin password (≥8 chars): ')).trim();
    rl.close();
  }
  if (!password || password.length < 8) {
    stderr.write('Password must be ≥8 characters.\n');
    process.exit(1);
  }

  const hash = await hashPassword(password);
  const now  = Math.floor(Date.now() / 1000);

  const lines = [
    '-- ════════════════════════════════════════════════════════════════',
    '-- Generated by worker-v2/bootstrap-users.js',
    '-- Two owner accounts, identical initial password (CHANGE AFTER LOGIN).',
    '-- Re-runnable: ON CONFLICT(email) updates the password_hash.',
    '-- ════════════════════════════════════════════════════════════════',
    '',
  ];

  for (const o of OWNERS) {
    lines.push(
      `INSERT INTO users (email, password_hash, role, status, display_name, created_at, updated_at) VALUES (` +
      [
        sqlString(o.email),
        sqlString(hash),
        `'owner'`,
        `'active'`,
        sqlString(o.display_name),
        now, now,
      ].join(', ') + `) ON CONFLICT(email) DO UPDATE SET ` +
        `password_hash = excluded.password_hash, ` +
        `role = 'owner', status = 'active', ` +
        `display_name = excluded.display_name, ` +
        `updated_at = ${now};`,
    );
  }
  lines.push('');

  process.stdout.write(lines.join('\n'));
  stderr.write(`\n✓ Generated SQL for ${OWNERS.length} owners.\n`);
  stderr.write(`✓ Apply with: wrangler d1 execute deafhive --remote --file=<the-file>\n`);
}

main().catch(err => {
  stderr.write(`FATAL: ${err.message}\n`);
  process.exit(1);
});
